/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WonderfulCardsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/CardRenderer.ts
var import_obsidian = require("obsidian");

// src/i18n.ts
var currentLang = "en";
var en = {
  // Commands
  "cmd.insert-template": "Insert magic item template",
  "cmd.open-catalog": "Open card catalog",
  // Card Renderer
  "card.parse-error": "Error parsing item card YAML.",
  "card.add-to-catalog": "Add to catalog",
  "card.remove-from-catalog": "Remove from catalog",
  "card.removed-notice": '"{name}" removed from catalog',
  "card.added-notice": '"{name}" added to catalog',
  "card.unknown-item": "Unknown item",
  "card.default-type": "Wondrous item",
  "card.requires-attunement": "requires attunement",
  "card.not-found": 'Card "{name}" not found in catalog',
  // Settings
  "settings.heading": "Catalog",
  "settings.add-card": "Add card",
  "settings.add-card-desc": "Create a new magic item card",
  "settings.add-btn": "+ Add",
  "settings.added-notice": '"{name}" added to catalog',
  "settings.empty": "Catalog is empty. Add your first card!",
  "settings.edit-btn": "Edit",
  "settings.updated-notice": '"{name}" updated',
  "settings.delete-btn": "Delete",
  "settings.deleted-notice": '"{name}" removed from catalog',
  "settings.language": "Language / \u042F\u0437\u044B\u043A",
  "settings.language-desc": "Select the plugin interface language",
  // Edit Modal
  "modal.title-edit": "Edit card",
  "modal.title-new": "New card",
  "modal.mode-gui": "Interface",
  "modal.mode-yaml": "YAML",
  "modal.save": "Save",
  "modal.cancel": "Cancel",
  "modal.name-required": "Please enter the item name",
  "modal.field-name": "Item name",
  "modal.field-title-en": "English title",
  "modal.field-image": "Image",
  "modal.field-type": "Type",
  "modal.field-subtype": "Subtype",
  "modal.field-rarity": "Rarity",
  "modal.field-attunement": "Requires attunement",
  "modal.field-price": "Price",
  "modal.field-align": "Text alignment",
  "modal.field-description": "Description",
  "modal.align-justify": "Justify",
  "modal.align-left": "Left",
  "modal.align-center": "Center",
  "modal.align-right": "Right",
  "modal.yaml-error": "YAML parsing error",
  // Template defaults
  "template.default-type": "Wondrous item",
  "template.default-align": "justify",
  // Catalog View
  "catalog.title": "Card catalog",
  "catalog.header": "Item catalog",
  "catalog.search-placeholder": "Search by name...",
  "catalog.empty": "Catalog is empty",
  "catalog.not-found": "Nothing found",
  // Preview View
  "preview.title": "Card preview",
  "preview.back": "\u2190 Back to catalog"
};
var ru = {
  // Commands
  "cmd.insert-template": "\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044C \u0448\u0430\u0431\u043B\u043E\u043D \u043C\u0430\u0433\u0438\u0447\u0435\u0441\u043A\u043E\u0433\u043E \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430",
  "cmd.open-catalog": "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u043A\u0430\u0442\u0430\u043B\u043E\u0433 \u043A\u0430\u0440\u0442\u043E\u0447\u0435\u043A",
  // Card Renderer
  "card.parse-error": "\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0430\u0440\u0441\u0438\u043D\u0433\u0430 YAML \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430.",
  "card.add-to-catalog": "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433",
  "card.remove-from-catalog": "\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0438\u0437 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0430",
  "card.removed-notice": "\xAB{name}\xBB \u0443\u0434\u0430\u043B\u0435\u043D\u0430 \u0438\u0437 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0430",
  "card.added-notice": "\xAB{name}\xBB \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0430 \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433",
  "card.unknown-item": "\u041D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442",
  "card.default-type": "\u0427\u0443\u0434\u0435\u0441\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442",
  "card.requires-attunement": "\u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430",
  "card.not-found": "\u041A\u0430\u0440\u0442\u043E\u0447\u043A\u0430 \xAB{name}\xBB \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u0430 \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0435",
  // Settings
  "settings.heading": "\u041A\u0430\u0442\u0430\u043B\u043E\u0433",
  "settings.add-card": "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443",
  "settings.add-card-desc": "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u043D\u043E\u0432\u0443\u044E \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443 \u043C\u0430\u0433\u0438\u0447\u0435\u0441\u043A\u043E\u0433\u043E \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430",
  "settings.add-btn": "+ \u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C",
  "settings.added-notice": "\xAB{name}\xBB \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0430 \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433",
  "settings.empty": "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u043F\u0443\u0441\u0442. \u0414\u043E\u0431\u0430\u0432\u044C\u0442\u0435 \u043F\u0435\u0440\u0432\u0443\u044E \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443!",
  "settings.edit-btn": "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C",
  "settings.updated-notice": "\xAB{name}\xBB \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0430",
  "settings.delete-btn": "\u0423\u0434\u0430\u043B\u0438\u0442\u044C",
  "settings.deleted-notice": "\xAB{name}\xBB \u0443\u0434\u0430\u043B\u0435\u043D\u0430 \u0438\u0437 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0430",
  "settings.language": "\u042F\u0437\u044B\u043A / Language",
  "settings.language-desc": "\u0412\u044B\u0431\u0435\u0440\u0438\u0442\u0435 \u044F\u0437\u044B\u043A \u0438\u043D\u0442\u0435\u0440\u0444\u0435\u0439\u0441\u0430 \u043F\u043B\u0430\u0433\u0438\u043D\u0430",
  // Edit Modal
  "modal.title-edit": "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443",
  "modal.title-new": "\u041D\u043E\u0432\u0430\u044F \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0430",
  "modal.mode-gui": "\u0418\u043D\u0442\u0435\u0440\u0444\u0435\u0439\u0441",
  "modal.mode-yaml": "YAML",
  "modal.save": "\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C",
  "modal.cancel": "\u041E\u0442\u043C\u0435\u043D\u0430",
  "modal.name-required": "\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430",
  "modal.field-name": "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430",
  "modal.field-title-en": "Item title (\u0410\u043D\u0433\u043B.)",
  "modal.field-image": "\u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435",
  "modal.field-type": "\u0422\u0438\u043F",
  "modal.field-subtype": "\u041F\u043E\u0434\u0442\u0438\u043F",
  "modal.field-rarity": "\u0420\u0435\u0434\u043A\u043E\u0441\u0442\u044C",
  "modal.field-attunement": "\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430",
  "modal.field-price": "\u0426\u0435\u043D\u0430",
  "modal.field-align": "\u0412\u044B\u0440\u0430\u0432\u043D\u0438\u0432\u0430\u043D\u0438\u0435 \u0442\u0435\u043A\u0441\u0442\u0430",
  "modal.field-description": "\u041E\u043F\u0438\u0441\u0430\u043D\u0438\u0435",
  "modal.align-justify": "\u041F\u043E \u0448\u0438\u0440\u0438\u043D\u0435",
  "modal.align-left": "\u041F\u043E \u043B\u0435\u0432\u043E\u043C\u0443 \u043A\u0440\u0430\u044E",
  "modal.align-center": "\u041F\u043E \u0446\u0435\u043D\u0442\u0440\u0443",
  "modal.align-right": "\u041F\u043E \u043F\u0440\u0430\u0432\u043E\u043C\u0443 \u043A\u0440\u0430\u044E",
  "modal.yaml-error": "\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0430\u0440\u0441\u0438\u043D\u0433\u0430 YAML",
  // Template defaults
  "template.default-type": "\u0427\u0443\u0434\u0435\u0441\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442",
  "template.default-align": "\u0448\u0438\u0440\u0438\u043D\u0430",
  // Catalog View
  "catalog.title": "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u043A\u0430\u0440\u0442\u043E\u0447\u0435\u043A",
  "catalog.header": "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u043E\u0432",
  "catalog.search-placeholder": "\u041F\u043E\u0438\u0441\u043A \u043F\u043E \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u044E...",
  "catalog.empty": "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u043F\u0443\u0441\u0442",
  "catalog.not-found": "\u041D\u0438\u0447\u0435\u0433\u043E \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u043E",
  // Preview View
  "preview.title": "\u041F\u0440\u0435\u0432\u044C\u044E \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438",
  "preview.back": "\u2190 \u041D\u0430\u0437\u0430\u0434 \u043A \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0443"
};
var dictionaries = { en, ru };
function setLang(lang) {
  currentLang = lang;
}
function t(key, params) {
  var _a, _b;
  let str = (_b = (_a = dictionaries[currentLang][key]) != null ? _a : dictionaries["en"][key]) != null ? _b : key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      str = str.replace(`{${k}}`, v);
    }
  }
  return str;
}

// src/CardRenderer.ts
function getRarityClass(rarity) {
  if (!rarity)
    return "wc-rarity--default";
  const r = rarity.toLowerCase().trim();
  if (r === "\u043E\u0431\u044B\u0447\u043D\u044B\u0439" || r === "\u043E\u0431\u044B\u0447\u043D\u043E\u0435" || r === "\u043E\u0431\u044B\u0447\u043D\u0430\u044F" || r === "common")
    return "wc-rarity--common";
  if (r === "\u043D\u0435\u043E\u0431\u044B\u0447\u043D\u044B\u0439" || r === "\u043D\u0435\u043E\u0431\u044B\u0447\u043D\u043E\u0435" || r === "\u043D\u0435\u043E\u0431\u044B\u0447\u043D\u0430\u044F" || r === "uncommon")
    return "wc-rarity--uncommon";
  if (r === "\u0440\u0435\u0434\u043A\u0438\u0439" || r === "\u0440\u0435\u0434\u043A\u043E\u0435" || r === "\u0440\u0435\u0434\u043A\u0430\u044F" || r === "rare")
    return "wc-rarity--rare";
  if (r.startsWith("\u043E\u0447\u0435\u043D\u044C \u0440\u0435\u0434\u043A") || r === "very rare")
    return "wc-rarity--veryrare";
  if (r === "\u043B\u0435\u0433\u0435\u043D\u0434\u0430\u0440\u043D\u044B\u0439" || r === "\u043B\u0435\u0433\u0435\u043D\u0434\u0430\u0440\u043D\u043E\u0435" || r === "\u043B\u0435\u0433\u0435\u043D\u0434\u0430\u0440\u043D\u0430\u044F" || r === "legendary")
    return "wc-rarity--legendary";
  if (r === "\u0430\u0440\u0442\u0435\u0444\u0430\u043A\u0442" || r === "artifact")
    return "wc-rarity--artifact";
  return "wc-rarity--default";
}
function getPriceCurrencyClass(price) {
  if (!price)
    return "";
  const p = price.toLowerCase().trim();
  if (p.endsWith("\u0437\u043C") || p.endsWith("gp"))
    return "wc-price--gold";
  if (p.endsWith("\u0441\u043C") || p.endsWith("sp"))
    return "wc-price--silver";
  if (p.endsWith("\u043C\u043C") || p.endsWith("cp"))
    return "wc-price--copper";
  if (p.endsWith("\u044D\u043C") || p.endsWith("ep"))
    return "wc-price--electrum";
  return "wc-price--gold";
}
var CardRenderer = class {
  static async render(app, source, el, sourcePath, component, options) {
    let item;
    try {
      item = (0, import_obsidian.parseYaml)(source);
    } catch (e) {
      el.createEl("div", { text: t("card.parse-error"), cls: "wc-card-error" });
      return;
    }
    el.addClass("wc-render-container");
    const rarityClass = getRarityClass(item.rarity);
    const card = el.createEl("div", { cls: `wc-card ${rarityClass}` });
    if (!(options == null ? void 0 : options.compact)) {
      const width = item.width && item.width >= 400 ? item.width : 400;
      card.setCssProps({ "--wc-card-width": `${width}px` });
      card.addClass("wc-card--custom-width");
    }
    if (options == null ? void 0 : options.onCardClick) {
      card.addClass("wc-card--clickable");
      card.addEventListener("click", (e) => {
        if (e.target.closest(".wc-block-action-btn"))
          return;
        options.onCardClick(item);
      });
    }
    card.createEl("div", { cls: "wc-card-accent" });
    if (!(options == null ? void 0 : options.compact) && ((options == null ? void 0 : options.onAddToCatalog) || (options == null ? void 0 : options.onRemoveFromCatalog))) {
      const actionContainer = el.createEl("div", { cls: "wc-block-action-container" });
      const addBtn = actionContainer.createEl("div", {
        cls: `clickable-icon wc-block-action-btn ${options.isInCatalog ? "wc-block-action-btn--added" : ""}`,
        attr: { "aria-label": options.isInCatalog ? t("card.remove-from-catalog") : t("card.add-to-catalog") }
      });
      const renderIcon = (isAdded2) => {
        addBtn.empty();
        if (isAdded2) {
          (0, import_obsidian.setIcon)(addBtn, "check");
        } else {
          (0, import_obsidian.setIcon)(addBtn, "plus");
        }
      };
      let isAdded = !!options.isInCatalog;
      renderIcon(isAdded);
      addBtn.addEventListener("click", (e) => {
        void (async () => {
          e.stopPropagation();
          if (isAdded && options.onRemoveFromCatalog) {
            await options.onRemoveFromCatalog(item);
            isAdded = false;
            addBtn.classList.remove("wc-block-action-btn--added");
            addBtn.setAttribute("aria-label", t("card.add-to-catalog"));
            renderIcon(isAdded);
            new import_obsidian.Notice(t("card.removed-notice", { name: item.name }));
          } else if (!isAdded && options.onAddToCatalog) {
            await options.onAddToCatalog(item, source);
            isAdded = true;
            addBtn.classList.add("wc-block-action-btn--added");
            addBtn.setAttribute("aria-label", t("card.remove-from-catalog"));
            renderIcon(isAdded);
            new import_obsidian.Notice(t("card.added-notice", { name: item.name }));
          }
        })();
      });
    }
    const headerRow = card.createEl("div", { cls: "wc-card-header-row" });
    const nameBlock = headerRow.createEl("div", { cls: "wc-card-name-block" });
    nameBlock.createEl("div", { text: item.name || t("card.unknown-item"), cls: "wc-card-name" });
    if (item.title_en) {
      nameBlock.createEl("div", { text: `[${item.title_en}]`, cls: "wc-card-name-en" });
    }
    if (item.price) {
      const currClass = getPriceCurrencyClass(item.price);
      headerRow.createEl("div", { text: item.price, cls: `wc-card-price-badge ${currClass}` });
    }
    const typeStr = item.type || t("card.default-type");
    let metaText = typeStr;
    if (item.subtype)
      metaText += ` (${item.subtype})`;
    if (item.rarity)
      metaText += `, ${item.rarity}`;
    if (item.attunement === true || String(item.attunement).toLowerCase() === "true") {
      metaText += ` (${t("card.requires-attunement")})`;
    } else if (typeof item.attunement === "string" && item.attunement.toLowerCase() !== "false" && item.attunement.trim() !== "") {
      metaText += ` (${item.attunement})`;
    }
    card.createEl("div", { text: metaText, cls: "wc-card-meta" });
    if (options == null ? void 0 : options.compact)
      return;
    card.createEl("div", { cls: "wc-card-divider" });
    if (item.image) {
      const imageWrap = card.createEl("div", { cls: "wc-card-image" });
      let imageString = item.image;
      if (!imageString.startsWith("![")) {
        if (imageString.startsWith("http")) {
          imageString = `![](${imageString})`;
        } else {
          imageString = `![[${imageString}]]`;
        }
      }
      await import_obsidian.MarkdownRenderer.render(app, imageString, imageWrap, sourcePath, component);
    }
    if (item.description) {
      const descDiv = card.createEl("div", { cls: "wc-card-description" });
      const alignMap = {
        "left": "left",
        "\u043B\u0435\u0432\u043E": "left",
        "center": "center",
        "\u0446\u0435\u043D\u0442\u0440": "center",
        "right": "right",
        "\u043F\u0440\u0430\u0432\u043E": "right",
        "justify": "justify",
        "\u0448\u0438\u0440\u0438\u043D\u0430": "justify"
      };
      const align = item.text_align ? alignMap[item.text_align.toLowerCase().trim()] || "justify" : "justify";
      descDiv.style.textAlign = align;
      await import_obsidian.MarkdownRenderer.render(app, item.description, descDiv, sourcePath, component);
    }
  }
};

// src/CatalogStore.ts
var import_obsidian2 = require("obsidian");
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substring(2, 9);
}
var CatalogStore = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.data = { catalog: [] };
  }
  async load() {
    const saved = await this.plugin.loadData();
    if (saved == null ? void 0 : saved.catalog) {
      this.data = saved;
    }
  }
  async save() {
    await this.plugin.saveData(this.data);
  }
  getAll() {
    return this.data.catalog;
  }
  getById(id) {
    return this.data.catalog.find((c) => c.id === id);
  }
  findByName(name) {
    return this.data.catalog.find(
      (c) => c.item.name.toLowerCase() === name.toLowerCase()
    );
  }
  search(query) {
    if (!query.trim())
      return this.data.catalog;
    const q = query.toLowerCase().trim();
    return this.data.catalog.filter(
      (c) => c.item.name.toLowerCase().includes(q) || c.item.title_en && c.item.title_en.toLowerCase().includes(q)
    );
  }
  async add(item, sourceYaml) {
    const entry = {
      id: generateId(),
      item: { ...item },
      sourceYaml
    };
    this.data.catalog.push(entry);
    await this.save();
    return entry;
  }
  async addFromYaml(yaml) {
    const item = (0, import_obsidian2.parseYaml)(yaml);
    return this.add(item, yaml);
  }
  async update(id, item, sourceYaml) {
    const idx = this.data.catalog.findIndex((c) => c.id === id);
    if (idx !== -1) {
      this.data.catalog[idx].item = { ...item };
      this.data.catalog[idx].sourceYaml = sourceYaml;
      await this.save();
    }
  }
  async remove(id) {
    this.data.catalog = this.data.catalog.filter((c) => c.id !== id);
    await this.save();
  }
  has(name) {
    return this.data.catalog.some(
      (c) => c.item.name.toLowerCase() === name.toLowerCase()
    );
  }
  getLang() {
    var _a;
    return (_a = this.data.lang) != null ? _a : "en";
  }
  async setLang(lang) {
    this.data.lang = lang;
    await this.save();
  }
};

// src/CatalogView.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_CATALOG = "wc-catalog-view";
var CatalogView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.searchQuery = "";
    this.plugin = plugin;
    this.component = new import_obsidian3.Component();
  }
  getViewType() {
    return VIEW_TYPE_CATALOG;
  }
  getDisplayText() {
    return t("catalog.title");
  }
  getIcon() {
    return "scroll";
  }
  async onOpen() {
    this.component.load();
    void this.renderView();
  }
  async onClose() {
    this.component.unload();
  }
  async renderView() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("wc-catalog-container");
    const header = container.createEl("div", { cls: "wc-catalog-header" });
    header.createEl("h3", { text: t("catalog.header") });
    const searchWrap = header.createEl("div", { cls: "wc-catalog-search-wrap" });
    const searchInput = searchWrap.createEl("input", {
      cls: "wc-catalog-search",
      attr: { type: "text", placeholder: t("catalog.search-placeholder") }
    });
    searchInput.value = this.searchQuery;
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      void this.renderGrid(grid);
    });
    const grid = container.createEl("div", { cls: "wc-catalog-grid" });
    await this.renderGrid(grid);
  }
  async renderGrid(grid) {
    grid.empty();
    const items = this.plugin.catalogStore.search(this.searchQuery);
    if (items.length === 0) {
      grid.createEl("div", {
        text: this.searchQuery ? t("catalog.not-found") : t("catalog.empty"),
        cls: "wc-catalog-empty"
      });
      return;
    }
    for (const entry of items) {
      const cardWrap = grid.createEl("div", { cls: "wc-catalog-mini-card-wrap" });
      await CardRenderer.render(
        this.app,
        entry.sourceYaml,
        cardWrap,
        "",
        this.component,
        {
          compact: true,
          onCardClick: () => {
            void this.plugin.openCardPreview(entry, true);
          }
        }
      );
    }
  }
  async refresh() {
    await this.renderView();
  }
};

// src/CardPreviewView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_CARD_PREVIEW = "wc-card-preview-view";
var CardPreviewView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.catalogItem = null;
    this.fromCatalog = false;
    this.plugin = plugin;
    this.component = new import_obsidian4.Component();
  }
  getViewType() {
    return VIEW_TYPE_CARD_PREVIEW;
  }
  getDisplayText() {
    return this.catalogItem ? this.catalogItem.item.name : t("preview.title");
  }
  getIcon() {
    return "eye";
  }
  async onOpen() {
    this.component.load();
    if (this.catalogItem) {
      await this.renderCard();
    }
  }
  async onClose() {
    this.component.unload();
  }
  async showCard(entry, fromCatalog = false) {
    this.catalogItem = entry;
    this.fromCatalog = fromCatalog;
    await this.renderCard();
  }
  async renderCard() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("wc-preview-container");
    if (this.fromCatalog) {
      const backBtn = container.createEl("button", {
        cls: "wc-preview-back-btn",
        text: t("preview.back")
      });
      backBtn.addEventListener("click", () => {
        void this.plugin.openCatalog();
      });
    }
    if (this.catalogItem) {
      const cardWrap = container.createEl("div", { cls: "wc-preview-card-wrap" });
      await CardRenderer.render(
        this.app,
        this.catalogItem.sourceYaml,
        cardWrap,
        "",
        this.component
      );
    }
  }
};

// src/SettingsTab.ts
var import_obsidian6 = require("obsidian");

// src/CardEditModal.ts
var import_obsidian5 = require("obsidian");
var CardEditModal = class extends import_obsidian5.Modal {
  constructor(app, plugin, editingItem, onSave) {
    super(app);
    this.mode = "gui";
    this.plugin = plugin;
    this.editingItem = editingItem;
    this.onSave = onSave;
    if (editingItem) {
      this.item = { ...editingItem.item };
      this.yamlText = editingItem.sourceYaml;
    } else {
      this.item = {
        name: "",
        title_en: "",
        image: "",
        type: t("card.default-type"),
        subtype: "",
        rarity: "",
        attunement: false,
        price: "",
        description: "",
        text_align: t("template.default-align")
      };
      this.yamlText = "";
    }
  }
  onOpen() {
    this.modalEl.addClass("wc-edit-modal");
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.editingItem ? t("modal.title-edit") : t("modal.title-new") });
    const toggleWrap = contentEl.createEl("div", { cls: "wc-edit-mode-toggle" });
    const guiBtn = toggleWrap.createEl("button", {
      text: t("modal.mode-gui"),
      cls: `wc-edit-mode-btn ${this.mode === "gui" ? "wc-edit-mode-btn--active" : ""}`
    });
    const yamlBtn = toggleWrap.createEl("button", {
      text: t("modal.mode-yaml"),
      cls: `wc-edit-mode-btn ${this.mode === "yaml" ? "wc-edit-mode-btn--active" : ""}`
    });
    guiBtn.addEventListener("click", () => {
      if (this.mode === "yaml") {
        this.syncYamlToItem();
      }
      this.mode = "gui";
      this.render();
    });
    yamlBtn.addEventListener("click", () => {
      if (this.mode === "gui") {
        this.syncItemToYaml();
      }
      this.mode = "yaml";
      this.render();
    });
    const body = contentEl.createEl("div", { cls: "wc-edit-body" });
    if (this.mode === "gui") {
      this.renderGUI(body);
    } else {
      this.renderYAML(body);
    }
    new import_obsidian5.Setting(contentEl).addButton((btn) => btn.setButtonText(t("modal.save")).setCta().onClick(() => {
      if (this.mode === "yaml")
        this.syncYamlToItem();
      if (this.mode === "gui")
        this.syncItemToYaml();
      if (!this.item.name) {
        new import_obsidian5.Notice(t("modal.name-required"));
        return;
      }
      this.onSave(this.item, this.yamlText);
      this.close();
    })).addButton((btn) => btn.setButtonText(t("modal.cancel")).onClick(() => this.close()));
  }
  renderGUI(container) {
    new import_obsidian5.Setting(container).setName(t("modal.field-name")).addText((tx) => tx.setValue(this.item.name).onChange((v) => {
      this.item.name = v;
    }));
    new import_obsidian5.Setting(container).setName(t("modal.field-title-en")).addText((tx) => tx.setValue(this.item.title_en || "").onChange((v) => {
      this.item.title_en = v;
    }));
    new import_obsidian5.Setting(container).setName(t("modal.field-image")).addText((tx) => tx.setValue(this.item.image || "").onChange((v) => {
      this.item.image = v;
    }));
    new import_obsidian5.Setting(container).setName(t("modal.field-type")).addText((tx) => tx.setValue(this.item.type).onChange((v) => {
      this.item.type = v || t("card.default-type");
    }));
    new import_obsidian5.Setting(container).setName(t("modal.field-subtype")).addText((tx) => tx.setValue(this.item.subtype || "").onChange((v) => {
      this.item.subtype = v;
    }));
    new import_obsidian5.Setting(container).setName(t("modal.field-rarity")).addText((tx) => tx.setValue(this.item.rarity || "").onChange((v) => {
      this.item.rarity = v;
    }));
    new import_obsidian5.Setting(container).setName(t("modal.field-attunement")).addToggle((tg) => tg.setValue(this.item.attunement === true || String(this.item.attunement).toLowerCase() === "true").onChange((v) => {
      this.item.attunement = v;
    }));
    new import_obsidian5.Setting(container).setName(t("modal.field-price")).addText((tx) => tx.setValue(this.item.price || "").onChange((v) => {
      this.item.price = v;
    }));
    new import_obsidian5.Setting(container).setName(t("modal.field-align")).addDropdown((d) => {
      var _a;
      const opts = {
        "justify": t("modal.align-justify"),
        "left": t("modal.align-left"),
        "center": t("modal.align-center"),
        "right": t("modal.align-right")
      };
      d.addOptions(opts);
      const legacyMap = {
        "\u0448\u0438\u0440\u0438\u043D\u0430": "justify",
        "\u043B\u0435\u0432\u043E": "left",
        "\u0446\u0435\u043D\u0442\u0440": "center",
        "\u043F\u0440\u0430\u0432\u043E": "right"
      };
      const currentVal = ((_a = this.item.text_align) == null ? void 0 : _a.toLowerCase().trim()) || "justify";
      const normalizedVal = legacyMap[currentVal] || currentVal;
      d.setValue(normalizedVal);
      d.onChange((v) => {
        this.item.text_align = v;
      });
    });
    new import_obsidian5.Setting(container).setName(t("modal.field-description")).addTextArea((tx) => {
      tx.inputEl.rows = 10;
      tx.inputEl.addClass("wc-edit-textarea");
      tx.setValue(this.item.description || "").onChange((v) => {
        this.item.description = v;
      });
    });
  }
  renderYAML(container) {
    if (!this.yamlText && this.item.name) {
      this.syncItemToYaml();
    }
    const ta = container.createEl("textarea", { cls: "wc-edit-yaml-area" });
    ta.value = this.yamlText;
    ta.rows = 20;
    ta.addEventListener("input", () => {
      this.yamlText = ta.value;
    });
  }
  syncItemToYaml() {
    const obj = {};
    if (this.item.name)
      obj.name = this.item.name;
    if (this.item.title_en)
      obj.title_en = this.item.title_en;
    if (this.item.image)
      obj.image = this.item.image;
    obj.type = this.item.type || t("card.default-type");
    if (this.item.subtype)
      obj.subtype = this.item.subtype;
    if (this.item.rarity)
      obj.rarity = this.item.rarity;
    obj.attunement = this.item.attunement === true || String(this.item.attunement).toLowerCase() === "true";
    if (this.item.price)
      obj.price = this.item.price;
    if (this.item.text_align)
      obj.text_align = this.item.text_align;
    if (this.item.description)
      obj.description = this.item.description;
    this.yamlText = (0, import_obsidian5.stringifyYaml)(obj).trim();
  }
  syncYamlToItem() {
    try {
      const parsed = (0, import_obsidian5.parseYaml)(this.yamlText);
      if (parsed) {
        this.item = { ...this.item, ...parsed };
      }
    } catch (e) {
      new import_obsidian5.Notice(t("modal.yaml-error"));
    }
  }
};

// src/SettingsTab.ts
var WonderfulCardsSettingsTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    this.renderSettings();
  }
  renderSettings() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian6.Setting(containerEl).setName(t("settings.language")).setDesc(t("settings.language-desc")).addDropdown((d) => d.addOptions({ "en": "English", "ru": "\u0420\u0443\u0441\u0441\u043A\u0438\u0439" }).setValue(this.plugin.catalogStore.getLang()).onChange((value) => {
      void (async () => {
        const lang = value;
        setLang(lang);
        await this.plugin.catalogStore.setLang(lang);
        this.renderSettings();
      })();
    }));
    new import_obsidian6.Setting(containerEl).setName(t("settings.heading")).setHeading();
    new import_obsidian6.Setting(containerEl).setName(t("settings.add-card")).setDesc(t("settings.add-card-desc")).addButton((btn) => btn.setButtonText(t("settings.add-btn")).setCta().onClick(() => {
      new CardEditModal(this.app, this.plugin, null, (item, yaml) => {
        void (async () => {
          await this.plugin.catalogStore.add(item, yaml);
          new import_obsidian6.Notice(t("settings.added-notice", { name: item.name }));
          this.renderSettings();
        })();
      }).open();
    }));
    containerEl.createEl("hr");
    const catalog = this.plugin.catalogStore.getAll();
    if (catalog.length === 0) {
      containerEl.createEl("p", {
        text: t("settings.empty"),
        cls: "wc-settings-empty"
      });
      return;
    }
    for (const entry of catalog) {
      const s = new import_obsidian6.Setting(containerEl).setName(entry.item.name).setDesc(`${entry.item.type || t("card.default-type")}${entry.item.rarity ? ", " + entry.item.rarity : ""}`);
      s.addButton((btn) => btn.setButtonText(t("settings.edit-btn")).onClick(() => {
        new CardEditModal(this.app, this.plugin, entry, (item, yaml) => {
          void (async () => {
            await this.plugin.catalogStore.update(entry.id, item, yaml);
            new import_obsidian6.Notice(t("settings.updated-notice", { name: item.name }));
            this.renderSettings();
          })();
        }).open();
      }));
      s.addButton((btn) => btn.setButtonText(t("settings.delete-btn")).setDestructive().onClick(() => {
        void (async () => {
          await this.plugin.catalogStore.remove(entry.id);
          new import_obsidian6.Notice(t("settings.deleted-notice", { name: entry.item.name }));
          this.renderSettings();
        })();
      }));
    }
  }
};

// src/main.ts
var WonderfulCardsPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    this.catalogStore = new CatalogStore(this);
    await this.catalogStore.load();
    setLang(this.catalogStore.getLang());
    this.registerView(VIEW_TYPE_CATALOG, (leaf) => new CatalogView(leaf, this));
    this.registerView(VIEW_TYPE_CARD_PREVIEW, (leaf) => new CardPreviewView(leaf, this));
    this.addSettingTab(new WonderfulCardsSettingsTab(this.app, this));
    this.registerMarkdownCodeBlockProcessor("itemcard", (source, el, ctx) => {
      const itemMatch = source.match(/name:\s*["']?([^"'\n]+)["']?/);
      const itemName = itemMatch ? itemMatch[1].trim() : "";
      const isInCatalog = this.catalogStore.has(itemName);
      void CardRenderer.render(this.app, source, el, ctx.sourcePath, this, {
        isInCatalog,
        onAddToCatalog: async (item, yaml) => {
          await this.catalogStore.add(item, yaml);
        },
        onRemoveFromCatalog: async (item) => {
          const c = this.catalogStore.findByName(item.name);
          if (c) {
            await this.catalogStore.remove(c.id);
          }
        },
        onCardClick: (item) => {
          const entry = this.catalogStore.findByName(item.name);
          if (entry) {
            void this.openCardPreview(entry);
          } else {
            void this.openCardPreview({ id: "temp", item, sourceYaml: source });
          }
        }
      });
    });
    this.addCommand({
      id: "insert-magic-item-template",
      name: t("cmd.insert-template"),
      editorCallback: (editor) => {
        const template = `\`\`\`itemcard
name: ""
title_en: ""
image: ""
type: "${t("template.default-type")}"
subtype: ""
rarity: ""
attunement: false
price: ""
text_align: "${t("template.default-align")}"
description: |
  
\`\`\`
`;
        editor.replaceSelection(template);
      }
    });
    this.addCommand({
      id: "open-catalog",
      name: t("cmd.open-catalog"),
      callback: () => {
        void this.openCatalog();
      }
    });
    this.registerMarkdownPostProcessor((element) => {
      element.querySelectorAll("code").forEach((code) => {
        if (code.textContent && code.textContent.trim().startsWith("wc:")) {
          code.addClass("wc-clickable-code");
        }
      });
    });
    this.registerDomEvent(activeDocument, "click", (evt) => {
      var _a, _b;
      const target = evt.target;
      const triggerPreview = (itemName) => {
        const entry = this.catalogStore.findByName(itemName);
        if (entry) {
          void this.openCardPreview(entry);
        } else {
          new import_obsidian7.Notice(t("card.not-found", { name: itemName }));
        }
      };
      const readingCode = target.closest("code.wc-clickable-code");
      if (readingCode) {
        let text = readingCode.textContent || "";
        text = text.replace(/`/g, "").trim();
        if (text.startsWith("wc:")) {
          evt.preventDefault();
          evt.stopPropagation();
          triggerPreview(text.substring(3).trim());
          return;
        }
      }
      if (evt.ctrlKey || evt.metaKey) {
        const cmInline = target.closest(".cm-inline-code");
        if (cmInline) {
          let text = cmInline.textContent || "";
          if (text === "`") {
            if ((_a = cmInline.nextElementSibling) == null ? void 0 : _a.classList.contains("cm-inline-code")) {
              text += cmInline.nextElementSibling.textContent || "";
            } else if ((_b = cmInline.previousElementSibling) == null ? void 0 : _b.classList.contains("cm-inline-code")) {
              text = (cmInline.previousElementSibling.textContent || "") + text;
            }
          }
          text = text.replace(/`/g, "").trim();
          if (text.startsWith("wc:")) {
            evt.preventDefault();
            evt.stopPropagation();
            triggerPreview(text.substring(3).trim());
            return;
          }
        }
      }
      const link = target.closest(".internal-link, .external-link");
      if (link) {
        const href = link.getAttribute("data-href") || link.getAttribute("href");
        if (href && href.startsWith("wc:")) {
          evt.preventDefault();
          evt.stopPropagation();
          triggerPreview(href.substring(3).trim());
        }
      }
    }, { capture: true });
  }
  onunload() {
  }
  async openCatalog() {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CATALOG)[0];
    if (!leaf) {
      const rightLeaf = this.app.workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({ type: VIEW_TYPE_CATALOG, active: true });
        leaf = rightLeaf;
      } else {
        return;
      }
    }
    await this.app.workspace.revealLeaf(leaf);
  }
  async openCardPreview(entry, fromCatalog = false) {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CARD_PREVIEW)[0];
    if (!leaf) {
      const rightLeaf = this.app.workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({ type: VIEW_TYPE_CARD_PREVIEW, active: true });
        leaf = rightLeaf;
      } else {
        return;
      }
    }
    await this.app.workspace.revealLeaf(leaf);
    if (leaf.view instanceof CardPreviewView) {
      await leaf.view.showCard(entry, fromCatalog);
    }
  }
};
