/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WonderfulCardsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/CardRenderer.ts
var import_obsidian = require("obsidian");
function getRarityClass(rarity) {
  if (!rarity)
    return "wc-rarity--default";
  const r = rarity.toLowerCase().trim();
  if (r === "\u043E\u0431\u044B\u0447\u043D\u044B\u0439" || r === "\u043E\u0431\u044B\u0447\u043D\u043E\u0435" || r === "\u043E\u0431\u044B\u0447\u043D\u0430\u044F")
    return "wc-rarity--common";
  if (r === "\u043D\u0435\u043E\u0431\u044B\u0447\u043D\u044B\u0439" || r === "\u043D\u0435\u043E\u0431\u044B\u0447\u043D\u043E\u0435" || r === "\u043D\u0435\u043E\u0431\u044B\u0447\u043D\u0430\u044F")
    return "wc-rarity--uncommon";
  if (r === "\u0440\u0435\u0434\u043A\u0438\u0439" || r === "\u0440\u0435\u0434\u043A\u043E\u0435" || r === "\u0440\u0435\u0434\u043A\u0430\u044F")
    return "wc-rarity--rare";
  if (r.startsWith("\u043E\u0447\u0435\u043D\u044C \u0440\u0435\u0434\u043A"))
    return "wc-rarity--veryrare";
  if (r === "\u043B\u0435\u0433\u0435\u043D\u0434\u0430\u0440\u043D\u044B\u0439" || r === "\u043B\u0435\u0433\u0435\u043D\u0434\u0430\u0440\u043D\u043E\u0435" || r === "\u043B\u0435\u0433\u0435\u043D\u0434\u0430\u0440\u043D\u0430\u044F")
    return "wc-rarity--legendary";
  if (r === "\u0430\u0440\u0442\u0435\u0444\u0430\u043A\u0442")
    return "wc-rarity--artifact";
  return "wc-rarity--default";
}
function getPriceCurrencyClass(price) {
  if (!price)
    return "";
  const p = price.toLowerCase().trim();
  if (p.endsWith("\u0437\u043C"))
    return "wc-price--gold";
  if (p.endsWith("\u0441\u043C"))
    return "wc-price--silver";
  if (p.endsWith("\u043C\u043C"))
    return "wc-price--copper";
  if (p.endsWith("\u044D\u043C"))
    return "wc-price--electrum";
  return "wc-price--gold";
}
var CardRenderer = class {
  static async render(app, source, el, sourcePath, component, options) {
    let item;
    try {
      item = (0, import_obsidian.parseYaml)(source);
    } catch (e) {
      el.createEl("div", { text: "\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0430\u0440\u0441\u0438\u043D\u0433\u0430 YAML \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430.", cls: "wc-card-error" });
      return;
    }
    el.addClass("wc-render-container");
    const rarityClass = getRarityClass(item.rarity);
    const card = el.createEl("div", { cls: `wc-card ${rarityClass}` });
    if (!(options == null ? void 0 : options.compact)) {
      const width = item.width && item.width >= 400 ? item.width : 400;
      card.style.width = `${width}px`;
      card.style.maxWidth = "100%";
    }
    if (options == null ? void 0 : options.onCardClick) {
      card.style.cursor = "pointer";
      card.addEventListener("click", (e) => {
        options.onCardClick(item);
      });
    }
    card.createEl("div", { cls: "wc-card-accent" });
    if (!(options == null ? void 0 : options.compact) && ((options == null ? void 0 : options.onAddToCatalog) || (options == null ? void 0 : options.onRemoveFromCatalog))) {
      const actionContainer = el.createEl("div", { cls: "wc-block-action-container" });
      const addBtn = actionContainer.createEl("div", {
        cls: `clickable-icon wc-block-action-btn ${options.isInCatalog ? "wc-block-action-btn--added" : ""}`,
        attr: { "aria-label": options.isInCatalog ? "\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0438\u0437 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0430" : "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433" }
      });
      const renderIcon = (isAdded2) => {
        if (isAdded2) {
          addBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path></svg>';
        } else {
          addBtn.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path><line x1="12" y1="7" x2="12" y2="13"></line><line x1="9" y1="10" x2="15" y2="10"></line></svg>';
        }
      };
      let isAdded = !!options.isInCatalog;
      renderIcon(isAdded);
      addBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        if (isAdded && options.onRemoveFromCatalog) {
          await options.onRemoveFromCatalog(item);
          isAdded = false;
          addBtn.classList.remove("wc-block-action-btn--added");
          addBtn.setAttribute("aria-label", "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433");
          renderIcon(isAdded);
          new import_obsidian.Notice(`\xAB${item.name}\xBB \u0443\u0434\u0430\u043B\u0435\u043D\u0430 \u0438\u0437 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0430`);
        } else if (!isAdded && options.onAddToCatalog) {
          await options.onAddToCatalog(item, source);
          isAdded = true;
          addBtn.classList.add("wc-block-action-btn--added");
          addBtn.setAttribute("aria-label", "\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0438\u0437 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0430");
          renderIcon(isAdded);
          new import_obsidian.Notice(`\xAB${item.name}\xBB \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0430 \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433`);
        }
      });
    }
    if (options == null ? void 0 : options.onCardClick) {
      card.style.cursor = "pointer";
      card.addEventListener("click", (e) => {
        if (e.target.closest(".wc-card-action-btn"))
          return;
        options.onCardClick(item);
      });
    }
    card.createEl("div", { cls: "wc-card-accent" });
    const headerRow = card.createEl("div", { cls: "wc-card-header-row" });
    const nameBlock = headerRow.createEl("div", { cls: "wc-card-name-block" });
    nameBlock.createEl("div", { text: item.name || "\u041D\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442", cls: "wc-card-name" });
    if (item.title_en) {
      nameBlock.createEl("div", { text: `[${item.title_en}]`, cls: "wc-card-name-en" });
    }
    if (item.price) {
      const currClass = getPriceCurrencyClass(item.price);
      headerRow.createEl("div", { text: item.price, cls: `wc-card-price-badge ${currClass}` });
    }
    const typeStr = item.type || "\u0427\u0443\u0434\u0435\u0441\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442";
    let metaText = typeStr;
    if (item.subtype)
      metaText += ` (${item.subtype})`;
    if (item.rarity)
      metaText += `, ${item.rarity}`;
    if (item.attunement === true || String(item.attunement).toLowerCase() === "true") {
      metaText += ` (\u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430)`;
    } else if (typeof item.attunement === "string" && item.attunement.toLowerCase() !== "false" && item.attunement.trim() !== "") {
      let att = item.attunement;
      if (att.toLowerCase().includes("\u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430")) {
        att = att.replace(/Требуется настройка/gi, "\u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430");
      }
      metaText += ` (${att})`;
    }
    card.createEl("div", { text: metaText, cls: "wc-card-meta" });
    if (options == null ? void 0 : options.compact)
      return;
    card.createEl("div", { cls: "wc-card-divider" });
    if (item.image) {
      const imageWrap = card.createEl("div", { cls: "wc-card-image" });
      let imageString = item.image;
      if (!imageString.startsWith("![")) {
        if (imageString.startsWith("http")) {
          imageString = `![](${imageString})`;
        } else {
          imageString = `![[${imageString}]]`;
        }
      }
      await import_obsidian.MarkdownRenderer.render(app, imageString, imageWrap, sourcePath, component);
    }
    if (item.description) {
      const descDiv = card.createEl("div", { cls: "wc-card-description" });
      const alignMap = {
        "left": "left",
        "\u043B\u0435\u0432\u043E": "left",
        "center": "center",
        "\u0446\u0435\u043D\u0442\u0440": "center",
        "right": "right",
        "\u043F\u0440\u0430\u0432\u043E": "right",
        "justify": "justify",
        "\u0448\u0438\u0440\u0438\u043D\u0430": "justify"
      };
      const align = item.text_align ? alignMap[item.text_align.toLowerCase().trim()] || "justify" : "justify";
      descDiv.style.textAlign = align;
      await import_obsidian.MarkdownRenderer.render(app, item.description, descDiv, sourcePath, component);
    }
  }
};

// src/CatalogStore.ts
var import_obsidian2 = require("obsidian");
function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).substring(2, 9);
}
var CatalogStore = class {
  constructor(plugin) {
    this.plugin = plugin;
    this.data = { catalog: [] };
  }
  async load() {
    const saved = await this.plugin.loadData();
    if (saved && saved.catalog) {
      this.data = saved;
    }
  }
  async save() {
    await this.plugin.saveData(this.data);
  }
  getAll() {
    return this.data.catalog;
  }
  getById(id) {
    return this.data.catalog.find((c) => c.id === id);
  }
  findByName(name) {
    return this.data.catalog.find(
      (c) => c.item.name.toLowerCase() === name.toLowerCase()
    );
  }
  search(query) {
    if (!query.trim())
      return this.data.catalog;
    const q = query.toLowerCase().trim();
    return this.data.catalog.filter(
      (c) => c.item.name.toLowerCase().includes(q) || c.item.title_en && c.item.title_en.toLowerCase().includes(q)
    );
  }
  async add(item, sourceYaml) {
    const entry = {
      id: generateId(),
      item: { ...item },
      sourceYaml
    };
    this.data.catalog.push(entry);
    await this.save();
    return entry;
  }
  async addFromYaml(yaml) {
    const item = (0, import_obsidian2.parseYaml)(yaml);
    return this.add(item, yaml);
  }
  async update(id, item, sourceYaml) {
    const idx = this.data.catalog.findIndex((c) => c.id === id);
    if (idx !== -1) {
      this.data.catalog[idx].item = { ...item };
      this.data.catalog[idx].sourceYaml = sourceYaml;
      await this.save();
    }
  }
  async remove(id) {
    this.data.catalog = this.data.catalog.filter((c) => c.id !== id);
    await this.save();
  }
  has(name) {
    return this.data.catalog.some(
      (c) => c.item.name.toLowerCase() === name.toLowerCase()
    );
  }
};

// src/CatalogView.ts
var import_obsidian3 = require("obsidian");
var VIEW_TYPE_CATALOG = "wc-catalog-view";
var CatalogView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.searchQuery = "";
    this.plugin = plugin;
    this.component = new import_obsidian3.Component();
  }
  getViewType() {
    return VIEW_TYPE_CATALOG;
  }
  getDisplayText() {
    return "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u043A\u0430\u0440\u0442\u043E\u0447\u0435\u043A";
  }
  getIcon() {
    return "scroll";
  }
  async onOpen() {
    this.component.load();
    this.renderView();
  }
  async onClose() {
    this.component.unload();
  }
  async renderView() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("wc-catalog-container");
    const header = container.createEl("div", { cls: "wc-catalog-header" });
    header.createEl("h3", { text: "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u043E\u0432" });
    const searchWrap = header.createEl("div", { cls: "wc-catalog-search-wrap" });
    const searchInput = searchWrap.createEl("input", {
      cls: "wc-catalog-search",
      attr: { type: "text", placeholder: "\u041F\u043E\u0438\u0441\u043A \u043F\u043E \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u044E..." }
    });
    searchInput.value = this.searchQuery;
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      this.renderGrid(grid);
    });
    const grid = container.createEl("div", { cls: "wc-catalog-grid" });
    await this.renderGrid(grid);
  }
  async renderGrid(grid) {
    grid.empty();
    const items = this.plugin.catalogStore.search(this.searchQuery);
    if (items.length === 0) {
      grid.createEl("div", {
        text: this.searchQuery ? "\u041D\u0438\u0447\u0435\u0433\u043E \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u043E" : "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u043F\u0443\u0441\u0442",
        cls: "wc-catalog-empty"
      });
      return;
    }
    for (const entry of items) {
      const cardWrap = grid.createEl("div", { cls: "wc-catalog-mini-card-wrap" });
      await CardRenderer.render(
        this.app,
        entry.sourceYaml,
        cardWrap,
        "",
        this.component,
        {
          compact: true,
          onCardClick: () => {
            this.plugin.openCardPreview(entry, true);
          }
        }
      );
    }
  }
  async refresh() {
    await this.renderView();
  }
};

// src/CardPreviewView.ts
var import_obsidian4 = require("obsidian");
var VIEW_TYPE_CARD_PREVIEW = "wc-card-preview-view";
var CardPreviewView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.catalogItem = null;
    this.fromCatalog = false;
    this.plugin = plugin;
    this.component = new import_obsidian4.Component();
  }
  getViewType() {
    return VIEW_TYPE_CARD_PREVIEW;
  }
  getDisplayText() {
    return this.catalogItem ? this.catalogItem.item.name : "\u041F\u0440\u0435\u0432\u044C\u044E \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0438";
  }
  getIcon() {
    return "eye";
  }
  async onOpen() {
    this.component.load();
    if (this.catalogItem) {
      await this.renderCard();
    }
  }
  async onClose() {
    this.component.unload();
  }
  async showCard(entry, fromCatalog = false) {
    this.catalogItem = entry;
    this.fromCatalog = fromCatalog;
    await this.renderCard();
  }
  async renderCard() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("wc-preview-container");
    if (this.fromCatalog) {
      const backBtn = container.createEl("button", {
        cls: "wc-preview-back-btn",
        text: "\u2190 \u041D\u0430\u0437\u0430\u0434 \u043A \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0443"
      });
      backBtn.addEventListener("click", () => {
        this.plugin.openCatalog();
      });
    }
    if (this.catalogItem) {
      const cardWrap = container.createEl("div", { cls: "wc-preview-card-wrap" });
      await CardRenderer.render(
        this.app,
        this.catalogItem.sourceYaml,
        cardWrap,
        "",
        this.component
      );
    }
  }
};

// src/SettingsTab.ts
var import_obsidian6 = require("obsidian");

// src/CardEditModal.ts
var import_obsidian5 = require("obsidian");
var CardEditModal = class extends import_obsidian5.Modal {
  constructor(app, plugin, editingItem, onSave) {
    super(app);
    this.mode = "gui";
    this.plugin = plugin;
    this.editingItem = editingItem;
    this.onSave = onSave;
    if (editingItem) {
      this.item = { ...editingItem.item };
      this.yamlText = editingItem.sourceYaml;
    } else {
      this.item = {
        name: "",
        title_en: "",
        image: "",
        type: "\u0427\u0443\u0434\u0435\u0441\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442",
        subtype: "",
        rarity: "",
        attunement: false,
        price: "",
        description: "",
        text_align: "\u0448\u0438\u0440\u0438\u043D\u0430"
      };
      this.yamlText = "";
    }
  }
  onOpen() {
    this.modalEl.addClass("wc-edit-modal");
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  render() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.editingItem ? "\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443" : "\u041D\u043E\u0432\u0430\u044F \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0430" });
    const toggleWrap = contentEl.createEl("div", { cls: "wc-edit-mode-toggle" });
    const guiBtn = toggleWrap.createEl("button", {
      text: "\u0418\u043D\u0442\u0435\u0440\u0444\u0435\u0439\u0441",
      cls: `wc-edit-mode-btn ${this.mode === "gui" ? "wc-edit-mode-btn--active" : ""}`
    });
    const yamlBtn = toggleWrap.createEl("button", {
      text: "YAML",
      cls: `wc-edit-mode-btn ${this.mode === "yaml" ? "wc-edit-mode-btn--active" : ""}`
    });
    guiBtn.addEventListener("click", () => {
      if (this.mode === "yaml") {
        this.syncYamlToItem();
      }
      this.mode = "gui";
      this.render();
    });
    yamlBtn.addEventListener("click", () => {
      if (this.mode === "gui") {
        this.syncItemToYaml();
      }
      this.mode = "yaml";
      this.render();
    });
    const body = contentEl.createEl("div", { cls: "wc-edit-body" });
    if (this.mode === "gui") {
      this.renderGUI(body);
    } else {
      this.renderYAML(body);
    }
    new import_obsidian5.Setting(contentEl).addButton((btn) => btn.setButtonText("\u0421\u043E\u0445\u0440\u0430\u043D\u0438\u0442\u044C").setCta().onClick(() => {
      if (this.mode === "yaml")
        this.syncYamlToItem();
      if (this.mode === "gui")
        this.syncItemToYaml();
      if (!this.item.name) {
        new import_obsidian5.Notice("\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u043D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430");
        return;
      }
      this.onSave(this.item, this.yamlText);
      this.close();
    })).addButton((btn) => btn.setButtonText("\u041E\u0442\u043C\u0435\u043D\u0430").onClick(() => this.close()));
  }
  renderGUI(container) {
    new import_obsidian5.Setting(container).setName("\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430").addText((t) => t.setValue(this.item.name).onChange((v) => {
      this.item.name = v;
    }));
    new import_obsidian5.Setting(container).setName("Item title (\u0410\u043D\u0433\u043B.)").addText((t) => t.setValue(this.item.title_en || "").onChange((v) => {
      this.item.title_en = v;
    }));
    new import_obsidian5.Setting(container).setName("\u0418\u0437\u043E\u0431\u0440\u0430\u0436\u0435\u043D\u0438\u0435").addText((t) => t.setValue(this.item.image || "").onChange((v) => {
      this.item.image = v;
    }));
    new import_obsidian5.Setting(container).setName("\u0422\u0438\u043F").addText((t) => t.setValue(this.item.type).onChange((v) => {
      this.item.type = v || "\u0427\u0443\u0434\u0435\u0441\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442";
    }));
    new import_obsidian5.Setting(container).setName("\u041F\u043E\u0434\u0442\u0438\u043F").addText((t) => t.setValue(this.item.subtype || "").onChange((v) => {
      this.item.subtype = v;
    }));
    new import_obsidian5.Setting(container).setName("\u0420\u0435\u0434\u043A\u043E\u0441\u0442\u044C").addText((t) => t.setValue(this.item.rarity || "").onChange((v) => {
      this.item.rarity = v;
    }));
    new import_obsidian5.Setting(container).setName("\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0430").addToggle((t) => t.setValue(this.item.attunement === true || String(this.item.attunement).toLowerCase() === "true").onChange((v) => {
      this.item.attunement = v;
    }));
    new import_obsidian5.Setting(container).setName("\u0426\u0435\u043D\u0430").addText((t) => t.setValue(this.item.price || "").onChange((v) => {
      this.item.price = v;
    }));
    new import_obsidian5.Setting(container).setName("\u0412\u044B\u0440\u0430\u0432\u043D\u0438\u0432\u0430\u043D\u0438\u0435 \u0442\u0435\u043A\u0441\u0442\u0430").addDropdown((d) => d.addOptions({ "\u0448\u0438\u0440\u0438\u043D\u0430": "\u041F\u043E \u0448\u0438\u0440\u0438\u043D\u0435", "\u043B\u0435\u0432\u043E": "\u041F\u043E \u043B\u0435\u0432\u043E\u043C\u0443 \u043A\u0440\u0430\u044E", "\u0446\u0435\u043D\u0442\u0440": "\u041F\u043E \u0446\u0435\u043D\u0442\u0440\u0443", "\u043F\u0440\u0430\u0432\u043E": "\u041F\u043E \u043F\u0440\u0430\u0432\u043E\u043C\u0443 \u043A\u0440\u0430\u044E" }).setValue(this.item.text_align || "\u0448\u0438\u0440\u0438\u043D\u0430").onChange((v) => {
      this.item.text_align = v;
    }));
    new import_obsidian5.Setting(container).setName("\u041E\u043F\u0438\u0441\u0430\u043D\u0438\u0435").addTextArea((t) => {
      t.inputEl.rows = 10;
      t.inputEl.addClass("wc-edit-textarea");
      t.setValue(this.item.description || "").onChange((v) => {
        this.item.description = v;
      });
    });
  }
  renderYAML(container) {
    if (!this.yamlText && this.item.name) {
      this.syncItemToYaml();
    }
    const ta = container.createEl("textarea", { cls: "wc-edit-yaml-area" });
    ta.value = this.yamlText;
    ta.rows = 20;
    ta.addEventListener("input", () => {
      this.yamlText = ta.value;
    });
  }
  syncItemToYaml() {
    const obj = {};
    if (this.item.name)
      obj.name = this.item.name;
    if (this.item.title_en)
      obj.title_en = this.item.title_en;
    if (this.item.image)
      obj.image = this.item.image;
    obj.type = this.item.type || "\u0427\u0443\u0434\u0435\u0441\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442";
    if (this.item.subtype)
      obj.subtype = this.item.subtype;
    if (this.item.rarity)
      obj.rarity = this.item.rarity;
    obj.attunement = this.item.attunement === true || String(this.item.attunement).toLowerCase() === "true";
    if (this.item.price)
      obj.price = this.item.price;
    if (this.item.text_align)
      obj.text_align = this.item.text_align;
    if (this.item.description)
      obj.description = this.item.description;
    this.yamlText = (0, import_obsidian5.stringifyYaml)(obj).trim();
  }
  syncYamlToItem() {
    try {
      const parsed = (0, import_obsidian5.parseYaml)(this.yamlText);
      if (parsed) {
        this.item = { ...this.item, ...parsed };
      }
    } catch (e) {
      new import_obsidian5.Notice("\u041E\u0448\u0438\u0431\u043A\u0430 \u043F\u0430\u0440\u0441\u0438\u043D\u0433\u0430 YAML");
    }
  }
};

// src/SettingsTab.ts
var WonderfulCardsSettingsTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Wonderful Cards \u2014 \u041A\u0430\u0442\u0430\u043B\u043E\u0433" });
    new import_obsidian6.Setting(containerEl).setName("\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443").setDesc("\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u043D\u043E\u0432\u0443\u044E \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443 \u043C\u0430\u0433\u0438\u0447\u0435\u0441\u043A\u043E\u0433\u043E \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430").addButton((btn) => btn.setButtonText("+ \u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C").setCta().onClick(() => {
      new CardEditModal(this.app, this.plugin, null, async (item, yaml) => {
        await this.plugin.catalogStore.add(item, yaml);
        new import_obsidian6.Notice(`\xAB${item.name}\xBB \u0434\u043E\u0431\u0430\u0432\u043B\u0435\u043D\u0430 \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433`);
        this.display();
      }).open();
    }));
    containerEl.createEl("hr");
    const catalog = this.plugin.catalogStore.getAll();
    if (catalog.length === 0) {
      containerEl.createEl("p", {
        text: "\u041A\u0430\u0442\u0430\u043B\u043E\u0433 \u043F\u0443\u0441\u0442. \u0414\u043E\u0431\u0430\u0432\u044C\u0442\u0435 \u043F\u0435\u0440\u0432\u0443\u044E \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443!",
        cls: "wc-settings-empty"
      });
      return;
    }
    for (const entry of catalog) {
      const s = new import_obsidian6.Setting(containerEl).setName(entry.item.name).setDesc(`${entry.item.type || "\u0427\u0443\u0434\u0435\u0441\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442"}${entry.item.rarity ? ", " + entry.item.rarity : ""}`);
      s.addButton((btn) => btn.setButtonText("\u0420\u0435\u0434\u0430\u043A\u0442\u0438\u0440\u043E\u0432\u0430\u0442\u044C").onClick(() => {
        new CardEditModal(this.app, this.plugin, entry, async (item, yaml) => {
          await this.plugin.catalogStore.update(entry.id, item, yaml);
          new import_obsidian6.Notice(`\xAB${item.name}\xBB \u043E\u0431\u043D\u043E\u0432\u043B\u0435\u043D\u0430`);
          this.display();
        }).open();
      }));
      s.addButton((btn) => btn.setButtonText("\u0423\u0434\u0430\u043B\u0438\u0442\u044C").setWarning().onClick(async () => {
        await this.plugin.catalogStore.remove(entry.id);
        new import_obsidian6.Notice(`\xAB${entry.item.name}\xBB \u0443\u0434\u0430\u043B\u0435\u043D\u0430 \u0438\u0437 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0430`);
        this.display();
      }));
    }
  }
};

// src/main.ts
var WonderfulCardsPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    this.catalogStore = new CatalogStore(this);
    await this.catalogStore.load();
    this.registerView(VIEW_TYPE_CATALOG, (leaf) => new CatalogView(leaf, this));
    this.registerView(VIEW_TYPE_CARD_PREVIEW, (leaf) => new CardPreviewView(leaf, this));
    this.addSettingTab(new WonderfulCardsSettingsTab(this.app, this));
    this.registerMarkdownCodeBlockProcessor("itemcard", (source, el, ctx) => {
      const itemMatch = source.match(/name:\s*["']?([^"'\n]+)["']?/);
      const itemName = itemMatch ? itemMatch[1].trim() : "";
      const isInCatalog = this.catalogStore.has(itemName);
      CardRenderer.render(this.app, source, el, ctx.sourcePath, this, {
        isInCatalog,
        onAddToCatalog: async (item, yaml) => {
          await this.catalogStore.add(item, yaml);
        },
        onRemoveFromCatalog: async (item) => {
          const c = this.catalogStore.findByName(item.name);
          if (c) {
            await this.catalogStore.remove(c.id);
          }
        },
        onCardClick: (item) => {
          const entry = this.catalogStore.findByName(item.name);
          if (entry) {
            this.openCardPreview(entry);
          } else {
            this.openCardPreview({ id: "temp", item, sourceYaml: source });
          }
        }
      });
    });
    this.addCommand({
      id: "insert-magic-item-template",
      name: "\u0412\u0441\u0442\u0430\u0432\u0438\u0442\u044C \u0448\u0430\u0431\u043B\u043E\u043D \u043C\u0430\u0433\u0438\u0447\u0435\u0441\u043A\u043E\u0433\u043E \u043F\u0440\u0435\u0434\u043C\u0435\u0442\u0430",
      editorCallback: (editor, view) => {
        const template = `\`\`\`itemcard
name: ""
title_en: ""
image: ""
type: "\u0427\u0443\u0434\u0435\u0441\u043D\u044B\u0439 \u043F\u0440\u0435\u0434\u043C\u0435\u0442"
subtype: ""
rarity: ""
attunement: false
price: ""
text_align: "\u0448\u0438\u0440\u0438\u043D\u0430"
description: |
  
\`\`\`
`;
        editor.replaceSelection(template);
      }
    });
    this.addCommand({
      id: "open-wonderful-cards-catalog",
      name: "\u041E\u0442\u043A\u0440\u044B\u0442\u044C \u043A\u0430\u0442\u0430\u043B\u043E\u0433 \u043A\u0430\u0440\u0442\u043E\u0447\u0435\u043A",
      callback: () => this.openCatalog()
    });
    this.registerMarkdownPostProcessor((element) => {
      element.querySelectorAll("code").forEach((code) => {
        if (code.textContent && code.textContent.trim().startsWith("wc:")) {
          code.addClass("wc-clickable-code");
        }
      });
    });
    this.registerDomEvent(document, "click", (evt) => {
      var _a, _b;
      const target = evt.target;
      const triggerPreview = (itemName) => {
        const entry = this.catalogStore.findByName(itemName);
        if (entry) {
          this.openCardPreview(entry);
        } else {
          new Notice(`\u041A\u0430\u0440\u0442\u043E\u0447\u043A\u0430 \xAB${itemName}\xBB \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u0430 \u0432 \u043A\u0430\u0442\u0430\u043B\u043E\u0433\u0435`);
        }
      };
      const readingCode = target.closest("code.wc-clickable-code");
      if (readingCode) {
        let text = readingCode.textContent || "";
        text = text.replace(/`/g, "").trim();
        if (text.startsWith("wc:")) {
          evt.preventDefault();
          evt.stopPropagation();
          triggerPreview(text.substring(3).trim());
          return;
        }
      }
      if (evt.ctrlKey || evt.metaKey) {
        const cmInline = target.closest(".cm-inline-code");
        if (cmInline) {
          let text = cmInline.textContent || "";
          if (text === "`") {
            if ((_a = cmInline.nextElementSibling) == null ? void 0 : _a.classList.contains("cm-inline-code")) {
              text += cmInline.nextElementSibling.textContent || "";
            } else if ((_b = cmInline.previousElementSibling) == null ? void 0 : _b.classList.contains("cm-inline-code")) {
              text = (cmInline.previousElementSibling.textContent || "") + text;
            }
          }
          text = text.replace(/`/g, "").trim();
          if (text.startsWith("wc:")) {
            evt.preventDefault();
            evt.stopPropagation();
            triggerPreview(text.substring(3).trim());
            return;
          }
        }
      }
      const link = target.closest(".internal-link, .external-link");
      if (link) {
        const href = link.getAttribute("data-href") || link.getAttribute("href");
        if (href && href.startsWith("wc:")) {
          evt.preventDefault();
          evt.stopPropagation();
          triggerPreview(href.substring(3).trim());
        }
      }
    }, { capture: true });
  }
  onunload() {
  }
  async openCatalog() {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CATALOG)[0];
    if (!leaf) {
      const rightLeaf = this.app.workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({ type: VIEW_TYPE_CATALOG, active: true });
        leaf = rightLeaf;
      } else {
        return;
      }
    }
    this.app.workspace.revealLeaf(leaf);
  }
  async openCardPreview(entry, fromCatalog = false) {
    let leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CARD_PREVIEW)[0];
    if (!leaf) {
      const rightLeaf = this.app.workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({ type: VIEW_TYPE_CARD_PREVIEW, active: true });
        leaf = rightLeaf;
      } else {
        return;
      }
    }
    this.app.workspace.revealLeaf(leaf);
    if (leaf.view instanceof CardPreviewView) {
      leaf.view.showCard(entry, fromCatalog);
    }
  }
};
